version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    volumes:
     - .:/app
     - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - web

volumes:
  db-data: